### ISSUE TITLE
Typo - to do engage

### ISSUE THREAD

**Issue by markwhiting** [distillpub/post--safety-needs-social-scientists#2]
> We have started this process, but are eager for more conversations with social scientists about what experiments could be run, and encourage other AI safety efforts to do engage similarly.

Should probably be: 

> We have started this process, but are eager for more conversations with social scientists about what experiments could be run, and encourage other AI safety efforts **to ~~do~~ engage** similarly.

**Comment by girving** [comment]
Thank you!  Arvind relayed this along and it should be fixed in the repo.  Will be redeployed soon.

https://github.com/distillpub/post--safety-needs-social-scientists/commit/36dbd2eb37a19426e79ffdf48ea901eab1a12d9e (apologies for not citing you, commit was before I saw this issue)
